version: "2"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    ports:
      - "${HOST_OS_DB_PORT}:3306"
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile-php
    command: php artisan serve
    env_file: .env
    volumes:
      - .:/laravel_ddd
    ports:
      - "3456:3000"
    tty: true
    environment:
      - PROJECT_NAME=demo
volumes:
  db-data:
    driver: local
