FROM php:7-apache
RUN apt-get update && apt-get install -y \
  libfreetype6-dev libjpeg62-turbo-dev libpng-dev \
  git vim unzip \
  && docker-php-ext-install pdo_mysql mysqli mbstring gd iconv zip \
  && apt-get clean
# install composer
RUN useradd  --user-group --create-home --shell /bin/false app
RUN mkdir /laravel_ddd
WORKDIR /laravel_ddd
RUN chown -R app:app /laravel_ddd
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
USER app
